export const GET_PROJECT_LOADING= 'GET_PROJECT_LOADING';
export const GET_PROJECT_SUCCESS= 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILED= 'GET_PROJECT_FAILED';

export const ADD_PROJECT_FAILED= 'ADD_PROJECT_FAILED';